load("//buck2:verilator_sim.bzl", "verilator_model")
load("//buck2:cocotb_test.bzl", "cocotb_test")

verilator_model(
    name = "axi4s_skid_buffer_model",
    top_module = "axi4s_skid_buffer",
    deps = ["//common_hdl_lib/axi:axi4s_skid_buffer"],
    compile_args = ["-Wno-fatal"],
    visibility = ["PUBLIC"],
)

cocotb_test(
    name = "axi4s_skid_buffer_test",
    model = ":axi4s_skid_buffer_model",
    test_module = "axi4s_skid_buffer_tb",
    cocotb_lib_dir = "/home/poflynn/src/hardware-monorepo/.venv/lib/python3.13/site-packages/cocotb/libs",
    verilator_cpp = "/home/poflynn/src/hardware-monorepo/.venv/lib/python3.13/site-packages/cocotb/share/lib/verilator/verilator.cpp",
    venv = "/home/poflynn/src/hardware-monorepo/.venv",
    python_path = [
        "/home/poflynn/src/hardware-monorepo",
        "/home/poflynn/src/hardware-monorepo/testbench_lib/axi",
        "/home/poflynn/src/hardware-monorepo/testbench_lib/core",
        "/home/poflynn/src/hardware-monorepo/common_hdl_lib/axi/tb",
    ],
)
