load("//buck2:sv_library.bzl", "sv_library")

sv_library(
    name = "vector_muxcy",
    srcs = ["src/vector_muxcy.sv"],
    visibility = ["PUBLIC"],
)

sv_library(
    name = "modulo",
    srcs = ["src/modulo.sv"],
    visibility = ["PUBLIC"],
)
