load("//buck2:system_verilog.bzl", "sv_library")

sv_library(
    name = "fifo36e2_wrapper",
    srcs = ["src/fifo36e2_wrapper.sv"],
    deps = [
        "//verilator_xpm:xilinx_primitives",
    ],
    visibility = ["PUBLIC"],
)
